FROM php:fpm-stretch

RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        libpng-dev \
    && docker-php-ext-install \
        zip \
        intl \
		mysqli \
        pdo pdo_mysql\
        gd
    
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY php-project/ /var/www/php-project
WORKDIR /var/www/php-project/
RUN cd /var/www/php-project
#RUN git clone https://github.com/cmruizg1993/sai-ecaa.git .