version: '3'

services:
    #db:
    #    image: mariadb:10.3
    #    restart: always
    #    environment:
    #        MYSQL_ROOT_PASSWORD: xxxx4444
    #    volumes:
    #        - ./mysql:/var/lib/mysql
    #    ports:
    #        - 3306:3306
    #    networks:
    #        - symfony

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8101:80
        environment:
            PMA_USER: root
            PMA_HOST: mysql
            PMA_PASSWORD: Cr157i@n
            MYSQL_ROOT_PASSWORD: Cr157i@n
            
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - ./php-project/:/var/www/php-project/
        ports:
            - 8001:80
        networks:
            - symfony
    nginx-app:
        build:
            context: .
            dockerfile: Dockerfile-nginx-angular
        volumes:
            - ./angular-build/www:/usr/share/nginx/html
        ports:
            - 8002:80
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev
        volumes:
            - ./php-project/:/var/www/php-project/
        networks:
            - symfony
        depends_on:
            - mysql
    mysql:
        image: mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: xxxx4444
            MYSQL_ROOT_PASSWORD: Cr157i@n
            MYSQL_DATABASE: sai_ecaa
        ports:
            - 3308:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - symfony
networks:
    symfony:

